lib/documents_design_web/router.ex
defmodule DocumentsDesignWeb.Router do
  use DocumentsDesignWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :global do
    plug DocumentsDesignWeb.Plugs.NeedsFirstUser
    plug DocumentsDesignWeb.Plugs.SetUser
  end

  pipeline :admin do
    plug DocumentsDesignWeb.Plugs.NeedsFirstUser
    plug DocumentsDesignWeb.Plugs.NeedsAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", DocumentsDesignWeb do
    pipe_through :browser
    get "/register", AuthController, :register
    post "/register", AuthController, :do_register
    get "/verify", AuthController, :verify
    post "/verify", AuthController, :do_verify
    get "/login", AuthController, :login
    post "/login", AuthController, :do_login
  end

  scope "/admin", DocumentsDesignWeb do
    pipe_through [:browser, :global, :admin]
    get "/", AdminController, :index
    post "/tags", AdminController, :add_tag
    delete "/tag", AdminController, :delete_tag
    get "/tags", AdminController, :tags
    get "/sequence", AdminController, :sequence
    get "/info", AdminController, :info
    get "/projects", AdminController, :projects
    get "/projects/edit/:id", AdminController, :edit_project
    get "/projects/new", AdminController, :new_project
  end

  scope "/", DocumentsDesignWeb do
    pipe_through [:browser, :global]
    get "/", PageController, :index
    get "/index", PageController, :projects
    get "/project/:slug", PageController, :project

    scope "/auth" do
      get "/logout", AuthController, :logout
      get "/forgot", AuthController, :forgot
      post "/forgot", AuthController, :do_forgot
      get "/reset", AuthController, :reset
      post "/reset", AuthController, :do_reset
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", DocumentsDesignWeb do
  #   pipe_through :api
  # end
end

lib/documents_design_web/views/layout_view.ex
defmodule DocumentsDesignWeb.LayoutView do
  use DocumentsDesignWeb, :view
end

lib/documents_design_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>documents.design</title>
    <link rel="icon" href="<%= Routes.static_path(@conn, "/favicon.png") %>"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/admin.css") %>"/>
  </head>
  <body>
    <aside class="Menu">
      Menu
      <ul>
        <li><%= link "Projets", to: Routes.admin_path(@conn, :projects) %>
        <li><%= link "Séquence d'accueil", to: Routes.admin_path(@conn, :sequence) %>
        <li><%= link "Informations", to: Routes.admin_path(@conn, :info) %>
        <li><%= link "Tags", to: Routes.admin_path(@conn, :tags) %>
      </ul>
    </aside>
    <main role="main" class="Main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/admin.js") %>"></script>
  </body>
</html>

lib/documents_design_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>documents.design</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <%= if @conn.assigns.user do %>
      <div class="LoggedBar">Connecté en tant que <%= @conn.assigns.user.name %> - <%= link "déconnexion", to: Routes.auth_path(@conn, :logout) %></div>
    <% else %>
      <div class="LoggedBar"><%= link "connexion", to: Routes.auth_path(@conn, :login) %></div>
    <% end %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/documents_design_web/templates/layout/auth.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>documents.design · Authentification</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/admin.css") %>"/>
  </head>
  <body>
    <main class="Page Auth Auth--login">
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>

lib/documents_design_web/templates/layout/home.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>documents.design</title>
    <link rel="icon" href="<%= Routes.static_path(@conn, "/favicon.png") %>"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/main.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/main.js") %>"></script>
  </body>
</html>